### PR TITLE
fix(object): the return type of objectMap should be the return type o…

### LINKED ISSUE #45: `objectMap` has bad return type
https://github.com/antfu/utils/blob/6cc9a99faaca1767969a375fdb2f222130d196c8/src/object.ts#L32

The return type of objectMap may be `Record<NK, NV>` instead of `Record<K, V>`

### PR DESCRIPTION
**Pull request by s3xysteak**
### Description

It fixed the return type issue of  `objectMap`.

Before:

```ts
const val = objectMap({ one: 1, two: 2 }, (k, v) => [k, `${v}`]) // { one: '1', two: '2' }
// type of val will be `Record<string, number>`, but it actually is `Record<string, string>`
```

After:

```ts
const val = objectMap({ one: 1, two: 2 }, (k, v) => [k, `${v}`]) // { one: '1', two: '2' }
// type of val is `Record<string, string>`
```

### Linked Issues

Fixes #45

### Additional context

I have to assert the type of return value because it cannot be compatible with `{ [k: string]: NV; }` and `Record<NK, NV>` and I have no idea how to fix it.

### CODE REVIEW

**Review by antfu — APPROVED** [review]

File: src/object.ts [hunk 1]
```diff
@@ -29,12 +29,12 @@ import type { DeepMerge } from './types'
  * // { b: 2 }
  * ```
  */
-export function objectMap<K extends string, V, NK = K, NV = V>(obj: Record<K, V>, fn: (key: K, value: V) => [NK, NV] | undefined): Record<K, V> {
+export function objectMap<K extends string, V, NK extends string | number | symbol = K, NV = V>(obj: Record<K, V>, fn: (key: K, value: V) => [NK, NV] | undefined): Record<NK, NV> {
```
Comment (nandordudas) [inline src/object.ts:32]: Just for curiosity, what do you think using of `PropertyKey` instead of `string | number | symbol`.

Comment (s3xysteak) [reply src/object.ts:32]: > Just for curiosity, what do you think using of `PropertyKey` instead of `string | number | symbol`?

This idea of yours is better I think. I use `string | number | symbol` just because that's what VSCode suggests.

Comment (nandordudas) [reply src/object.ts:32]: Thanks for the honest answer.
